{
 "title": "OpenEBS / Node Volume Problem",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "About the Dashboard",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# *Node Problem Detector*\n---\n\nThe dashboard is used to detect problems with the nodes on which volumes are mounted on by watching the system logs.  \nSince npd takes different approach in detecting node problems (parsing system log or dmesg files), it may be hard to find the disk device causing the actual problem. So, this dashboard currently associates the node problem(if any) with all  the pvc provisioned on that bad node.  \n```\nIf there are no probelm with the node on which the volume is mounted then the problem counter(or metric value) for each of the panels below will be '0'. But if any problem occurs then the counter value( or metric value) is increased by 1 everytime that error occurs in the system logs. Each panel below resembles one specific type of error.  \n```\n         "
   }
  },
  {
   "title": "FilesystemIsReadOnly",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kubelet_volume_stats_inodes * 0) + on(node) group_left(reason) problem_counter{reason=\"FilesystemIsReadOnly\"}",
     "legendFormat": "Node: {{ node}}, PVC: {{ persistentvolumeclaim }} "
    }
   ]
  },
  {
   "title": "Ext4Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kubelet_volume_stats_inodes * 0) + on(node) group_left(reason) problem_counter{reason=\"Ext4Error\"}",
     "legendFormat": "Node: {{ node}}, PVC: {{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "IOError",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kubelet_volume_stats_inodes * 0) + on(node) group_left(reason) problem_counter{reason=\"IOError\"} ",
     "legendFormat": "Node: {{ node}}, PVC: {{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Ext4Warning",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kubelet_volume_stats_inodes * 0) + on(node) group_left(reason) problem_counter{reason=\"Ext4Warning\"} ",
     "legendFormat": "Node: {{ node}}, PVC: {{ persistentvolumeclaim }} "
    }
   ]
  }
 ]
}