groups:
  - name: openebs-cStor-pool
    rules:
      - alert: PoolCapacityLow
        annotations:
          componentType: "pool"
          cstorPool: "{{ $labels.cstor_pool }}"
          storageClassClaim: "{{ $labels.storage_pool_claim }}"
          description: |-
            OpenEBS Pool {{ $labels.cstor_pool }} use more than 80% of his capacity
          summary: 'cStor pool ''{{$labels.cstor_pool}}'' created for pool claim ''{{$labels.storage_pool_claim}}'' has {{ with printf "openebs_free_pool_capacity{cstor_pool=''%s'',instance=''%s'',job=''%s'',kubernetes_pod_name=''%s'',slave=''%s'',storage_pool_claim=''%s''}/(1024*1024*1024)" $labels.cstor_pool $labels.instance $labels.job $labels.kubernetes_pod_name $labels.slave $labels.storage_pool_claim | query }} {{ . | first | value }} {{ end }}GB space remaining out of {{ with printf "openebs_pool_size{cstor_pool=''%s'',instance=''%s'',job=''%s'',kubernetes_pod_name=''%s'',slave=''%s'',storage_pool_claim=''%s''}/(1024*1024*1024)" $labels.cstor_pool $labels.instance $labels.job $labels.kubernetes_pod_name $labels.slave $labels.storage_pool_claim | query }} {{ . | first | value }} {{ end }} GB. You have already consumed {{ $value }} percent of total capacity'
        expr: |-
          openebs_used_pool_capacity_percent > 80
        for: 2m
        labels:
          severity: "warning"

      - alert: PoolIsOffline
        annotations:
          componentType: "pool"
          cstorPool: "{{ $labels.cstor_pool }}"
          storageClassClaim: "{{ $labels.storage_pool_claim }}"
          description: |-
            cStor pool '{{$labels.cstor_pool}}' created for the claim '{{$labels.storage_pool_claim}}' is offline, your application consuming the storage could be impacted
          summary: |-
            cStor pool '{{$labels.cstor_pool}}' created for the claim '{{$labels.storage_pool_claim}}' has gone offline
        expr: |-
          (openebs_pool_status == 0 and (openebs_pool_status offset 1m != 0))
        for: 2m
        labels:
          severity: "error"

      - alert: PoolIsOnline
        annotations:
          componentType: "pool"
          cstorPool: "{{ $labels.cstor_pool }}"
          storageClassClaim: "{{ $labels.storage_pool_claim }}"
          description: |-
            cStor pool '{{$labels.cstor_pool}}' created for the pool claim '{{$labels.storage_pool_claim}}' is now online
          summary: |-
            cStor pool '{{$labels.cstor_pool}}' created for the pool claim '{{$labels.storage_pool_claim}}' is now online
        expr: |-
          (openebs_pool_status == 1 and (openebs_pool_status offset 1m != 1))
        for: 2m
        labels:
          severity: "info"

      - alert: PoolIsDegraded
        annotations:
          componentType: "pool"
          cstorPool: "{{ $labels.cstor_pool }}"
          storageClassClaim: "{{ $labels.storage_pool_claim }}"
          description: |-
            cStor pool '{{$labels.cstor_pool}}' created for the pool claim '{{$labels.storage_pool_claim}}' is in a degraded state
          summary: |-
            cStor pool '{{$labels.cstor_pool}}' created for the pool claim '{{$labels.storage_pool_claim}}' is now online
        expr: |-
          (openebs_pool_status == 2 and (openebs_pool_status offset 1m != 2))
        for: 2m
        labels:
          severity: "warning"

      - alert: PoolStatusIsFaulted
        annotations:
          componentType: "pool"
          cstorPool: "{{ $labels.cstor_pool }}"
          storageClassClaim: "{{ $labels.storage_pool_claim }}"
          description: |-
            cStor pool '{{$labels.cstor_pool}}' created for the pool claim '{{$labels.storage_pool_claim}}' is in faulted state, this typically indicates total failure of the disk, making it incapable of sending data to it or receiving data from it
          summary: |-
            cStor pool '{{$labels.cstor_pool}}' created for the pool claim '{{$labels.storage_pool_claim}}' has gone in faulted state
        expr: |-
          (openebs_pool_status == 3 and (openebs_pool_status offset 1m != 3))
        for: 2m
        labels:
          severity: "error"

      - alert: PoolStatusIsUnhealthy
        annotations:
          componentType: "pool"
          cstorPool: "{{ $labels.cstor_pool }}"
          storageClassClaim: "{{ $labels.storage_pool_claim }}"
          description: |-
            cStor pool '{{$labels.cstor_pool}}' created for the claim '{{$labels.storage_pool_claim}}' is in unhealthy state, check the pool and disk statuses
          summary: |-
            cStor pool '{{$labels.cstor_pool}}' created for the pool claim '{{$labels.storage_pool_claim}}' is in unhealthy state. Reads and Writes may not be happening on the pool.
        expr: |-
          (openebs_zpool_state_unknown == 1 and (openebs_zpool_state_unknown offset 75s != 1)) or ((openebs_zpool_last_sync_time offset 75s) == (openebs_zpool_last_sync_time))
        for: 2m
        labels:
          severity: "warning"

      - alert: PoolRecoveredFromUnhealthyState
        annotations:
          componentType: "pool"
          cstorPool: "{{ $labels.cstor_pool }}"
          storageClassClaim: "{{ $labels.storage_pool_claim }}"
          description: |-
            cStor pool '{{$labels.cstor_pool}}' created for the claim '{{$labels.storage_pool_claim}}' has recovered from an unhealthy state.
          summary: |-
            cStor pool '{{$labels.cstor_pool}}' created for the pool claim '{{$labels.storage_pool_claim}}' has recovered from an unhealthy state. Reads and Writes are happening on the pool
        expr: |-
          ((openebs_zpool_state_unknown == 0 and (openebs_zpool_state_unknown offset 75s != 0)) and (openebs_zpool_last_sync_time > openebs_zpool_last_sync_time offset 75s) and (openebs_zpool_last_sync_time offset 150s == openebs_zpool_last_sync_time offset 75s)) or ((openebs_zpool_state_unknown == 0 and (openebs_zpool_state_unknown offset 75s == 0)) and (openebs_zpool_last_sync_time > openebs_zpool_last_sync_time offset 75s) and (openebs_zpool_last_sync_time offset 150s == openebs_zpool_last_sync_time offset 75s))
        for: 2m
        labels:
          severity: "info"
