{
 "title": "OpenEBS / Node Device Manager(NDM)",
 "tags": [
  "OpenEBS",
  "NDM"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(node_block_device_state, nodename)"
   },
   {
    "name": "device",
    "label": "device",
    "query": "label_values(node_block_device_state{nodename=~\"$node\"}, path)"
   }
  ]
 },
 "panels": [
  {
   "title": "Block Device State",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_block_device_state{nodename=~\"$node\", path=~\"$device\"}",
     "legendFormat": "node: {{nodename}}, device: {{path}}"
    }
   ]
  },
  {
   "title": "No. of requests rejected by ndm cluster exporter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_reject_request_count", "legendFormat": "exporter pod: {{pod}}" }
   ]
  },
  {
   "title": "No. of requests errored out by ndm cluster exporter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_error_request_count", "legendFormat": "exporter pod: {{pod}}" }
   ]
  },
  {
   "title": "No. of requests rejected by ndm node exporter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "seachest_reject_request_count", "legendFormat": "exporter pod: {{pod}}" }
   ]
  },
  {
   "title": "No. of requests errored out by ndm node exporter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "seachest_error_request_count", "legendFormat": "exporter pod: {{pod}}" }
   ]
  },
  {
   "title": "Blockdevice Highest Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "seachest_block_device_highest_temperature_celsius{nodename=~\"$node\", path=~\"$device\"}",
     "legendFormat": "node: {{nodename}}, device: {{path}}"
    }
   ]
  },
  {
   "title": "Blockdevice Lowest Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "seachest_block_device_lowest_temperature_celsius{nodename=~\"$node\", path=~\"$device\"}",
     "legendFormat": "node: {{nodename}}, device: {{path}}"
    }
   ]
  },
  {
   "title": "Blockdevice Current Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "seachest_block_device_current_temperature_celsius{nodename=~\"$node\", path=~\"$device\"}",
     "legendFormat": "node: {{nodename}}, device: {{path}}"
    }
   ]
  },
  {
   "title": "Blockdevice Temperature Validity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "seachest_block_device_current_temperature_valid{nodename=~\"$node\", path=~\"$device\"}",
     "legendFormat": "node: {{nodename}}, device: {{path}}"
    }
   ]
  },
  {
   "title": "Blockdevice life% used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "seachest_block_device_endurance_used_percent{nodename=~\"$node\", path=~\"$device\"}",
     "legendFormat": "node: {{nodename}}, device: {{path}}"
    }
   ]
  },
  {
   "title": "Blockdevice Read Data",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "Bps", "label": "bytes read" }
   ],
   "targets": [
    {
     "expr": "rate(seachest_block_device_total_read_bytes{nodename=~\"$node\", path=~\"$device\"}[$__rate_interval])",
     "legendFormat": "node: {{nodename}}, device: {{path}}"
    }
   ]
  },
  {
   "title": "Blockdevice Write Data",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "Bps", "label": "bytes written" }
   ],
   "targets": [
    {
     "expr": "rate(seachest_block_device_total_written_bytes{nodename=~\"$node\", path=~\"$device\"}[$__rate_interval])",
     "legendFormat": "node: {{nodename}}, device: {{path}}"
    }
   ]
  },
  {
   "title": "Blockdevice Util%",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "percent", "label": "%util" }
   ],
   "targets": [
    {
     "expr": "rate(seachest_block_device_utilization_rate_percent{nodename=~\"$node\", path=~\"$device\"}[$__rate_interval])",
     "legendFormat": "node: {{nodename}}, device: {{path}}"
    }
   ]
  }
 ]
}