{
 "title": "LVM Pool",
 "tags": [ "LVM" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(node_uname_info, instance)"
   },
   {
    "name": "volume_group",
    "label": "volume_group",
    "query": "label_values(lvm_vg_total_size_bytes{instance=~\"$node.*\"}, name)"
   },
   { "name": "thinPool", "label": "thinPool", "query": "thin-pool" },
   { "name": "thinVolume", "label": "thinVolume", "query": "thin" },
   {
    "name": "thin_pool",
    "label": "thin_pool",
    "query": "label_values(lvm_lv_total_size_bytes{vg=~\"$volume_group\", segtype=~\"$thinPool\"},  name) "
   }
  ]
 },
 "panels": [
  { "title": "Volume group Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volume Group Capacity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lvm_vg_total_size_bytes{name=~\"$volume_group\"}",
     "legendFormat": "Total size"
    },
    {
     "expr": "lvm_vg_free_size_bytes{name=~\"$volume_group\"}",
     "legendFormat": "Free size"
    },
    {
     "expr": "lvm_vg_total_size_bytes{name=~\"$volume_group\"}-lvm_vg_free_size_bytes{name=~\"$volume_group\"}",
     "legendFormat": "Used size"
    }
   ]
  },
  {
   "title": "Volume Group Metadata Capacity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lvm_vg_mda_total_size_bytes{name=~\"$volume_group\"}",
     "legendFormat": "Metadata total size"
    },
    {
     "expr": "lvm_vg_mda_free_size_bytes{name=~\"$volume_group\"}",
     "legendFormat": "Metadata free size"
    },
    {
     "expr": "lvm_vg_mda_total_size_bytes{name=~\"$volume_group\"}-lvm_vg_mda_free_size_bytes{name=~\"$volume_group\"}",
     "legendFormat": "Metadata used size"
    }
   ]
  },
  {
   "title": "Volume Group Permission",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lvm_vg_permission{name=~\"$volume_group\"}",
     "legendFormat": "Permission"
    }
   ]
  },
  {
   "title": "Volume Group Allocation Policy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lvm_vg_allocation_policy{name=~\"$volume_group\"}",
     "legendFormat": "allocation policy"
    }
   ]
  },
  {
   "title": "Volume Group volumes count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lvm_vg_lv_count{name=~\"$volume_group\"}",
     "legendFormat": "current lv count"
    },
    {
     "expr": "lvm_vg_max_lv_count{name=~\"$volume_group\"}",
     "legendFormat": "max lv count"
    }
   ]
  },
  {
   "title": "Volume Group pv count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lvm_vg_pv_count{name=~\"$volume_group\"}",
     "legendFormat": "current pv count"
    },
    {
     "expr": "lvm_vg_missing_pv_count{name=~\"$volume_group\"}",
     "legendFormat": "missing pv count"
    },
    {
     "expr": "lvm_vg_max_pv_count{name=~\"$volume_group\"}",
     "legendFormat": "max pv count"
    }
   ]
  },
  {
   "title": "Volume Group metadata count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lvm_vg_mda_count{name=~\"$volume_group\"}",
     "legendFormat": "current metadata count"
    },
    {
     "expr": "lvm_vg_mda_used_count{name=~\"$volume_group\"}",
     "legendFormat": "used metadata count"
    }
   ]
  },
  {
   "title": "Volume Group snapshots count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lvm_vg_snap_count{name=~\"$volume_group\"}",
     "legendFormat": "snapshots count"
    }
   ]
  },
  {
   "title": "Volume Group Volumes",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "lvm_lv_used_percent{vg=~\"$volume_group\",segtype=~\"$thinVolume\"}"
    },
    {
     "expr": "lvm_lv_total_size_bytes{vg=~\"$volume_group\",segtype!=\"$thinPool\"}"
    }
   ]
  },
  { "title": "Volume Group Performance Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Volume Group IO Reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "iops", "label": "IO read" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{instance=~\"$node.*\"}[5m]) + on(device) group_left(name) (lvm_lv_when_full{vg=~\"$volume_group\"} * 0))",
     "legendFormat": "reads/sec"
    }
   ]
  },
  {
   "title": "Volume Group IO Writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "iops", "label": "IO write" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_writes_completed_total{instance=~\"$node.*\"}[5m]) + on(device) group_left(name) (lvm_lv_when_full{vg=~\"$volume_group\"} * 0))",
     "legendFormat": "writes/sec"
    }
   ]
  },
  {
   "title": "Volume Group R/W Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "Bps", "label": "bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=~\"$node.*\"}[5m]) + on(device) group_left(name) (lvm_lv_when_full{vg=~\"$volume_group\"} * 0))",
     "legendFormat": "Read bytes"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"$node.*\"}[5m]) + on(device) group_left(name) (lvm_lv_when_full{vg=~\"$volume_group\"} * 0))",
     "legendFormat": "Written bytes"
    }
   ]
  },
  {
   "title": "Volume Group I/O Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "percentunit", "label": "%util" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{instance=~\"$node.*\"}[5m]) + on(device) group_left(name) (lvm_lv_when_full{vg=~\"$volume_group\"} * 0))",
     "legendFormat": "utilization"
    }
   ]
  },
  { "title": "Thin Pool Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Health Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lvm_lv_health_status{name=~\"$thin_pool\"}",
     "legendFormat": "Health Status"
    }
   ]
  },
  {
   "title": "Behaviour when full",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lvm_lv_when_full{name=~\"$thin_pool\"}",
     "legendFormat": "behaviour"
    }
   ]
  },
  {
   "title": "Pool Capacity",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lvm_lv_total_size_bytes{name=~\"$thin_pool\"}",
     "legendFormat": "Total size"
    },
    {
     "expr": "lvm_lv_used_percent{name=~\"$thin_pool\"}",
     "legendFormat": "Used %"
    }
   ]
  },
  {
   "title": "Pool Metadata Capacity",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lvm_lv_mda_total_size_bytes{name=~\"$thin_pool\"}",
     "legendFormat": "Metadata size"
    },
    {
     "expr": "lvm_lv_mda_used_percent{name=~\"$thin_pool\"}",
     "legendFormat": "Metadata used %"
    }
   ]
  },
  {
   "title": "Pool Snapshot Full %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "lvm_lv_snap_percent{name=~\"$thin_pool\"}",
     "legendFormat": "snapshot full %"
    }
   ]
  },
  {
   "title": "Pool Permission",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lvm_lv_permission{name=~\"$thin_pool\"}",
     "legendFormat": "permission"
    }
   ]
  },
  {
   "title": "Thin Volumes",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "lvm_lv_used_percent{pool=~\"$thin_pool\",segtype=~\"$thinVolume\"}"
    },
    {
     "expr": "lvm_lv_total_size_bytes{pool=~\"$thin_pool\",segtype=~\"$thinVolume\"}"
    }
   ]
  },
  { "title": "Thin Pool Performance Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Thin Pool IO Reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "iops", "label": "IO read" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{instance=~\"$node.*\"}[5m]) + on(device) group_left(name) (lvm_lv_when_full{vg=~\"$volume_group\",segtype=~\"$thinVolume\"} * 0))",
     "legendFormat": "reads/sec"
    }
   ]
  },
  {
   "title": "Thin Pool IO Writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "iops", "label": "IO write" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_writes_completed_total{instance=~\"$node.*\"}[5m]) + on(device) group_left(name) (lvm_lv_when_full{vg=~\"$volume_group\",segtype=~\"$thinVolume\"} * 0))",
     "legendFormat": "writes/sec"
    }
   ]
  },
  {
   "title": "Thin Pool R/W Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "Bps", "label": "bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=~\"$node.*\"}[5m]) + on(device) group_left(name) (lvm_lv_when_full{vg=~\"$volume_group\",segtype=~\"$thinVolume\"} * 0))",
     "legendFormat": "Read bytes"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"$node.*\"}[5m]) + on(device) group_left(name) (lvm_lv_when_full{vg=~\"$volume_group\",segtype=~\"$thinVolume\"} * 0))",
     "legendFormat": "Written bytes"
    }
   ]
  },
  {
   "title": "Thin Pool Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "percentunit", "label": "%util" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{instance=~\"$node.*\"}[5m]) + on(device) group_left(name) (lvm_lv_when_full{vg=~\"$volume_group\",segtype=~\"$thinVolume\"} * 0))",
     "legendFormat": "utililization"
    }
   ]
  },
  { "title": "Volume Group PV Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Volume Group PV",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "lvm_pv_total_size_bytes{vg=~\"$volume_group\"}"
    },
    {
     "expr": "lvm_pv_used_size_bytes{vg=~\"$volume_group\"}"
    },
    {
     "expr": "lvm_pv_free_size_bytes{vg=~\"$volume_group\"}"
    },
    {
     "expr": "lvm_pv_device_size_bytes{vg=~\"$volume_group\"}"
    }
   ]
  }
 ]
}