{
 "title": "OpenEBS / cStor / Pool dashboard",
 "tags": [ "OpenEBS" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cstor_pool",
    "query": "label_values(openebs_pool_status, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "cStor Pool Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openebs_pool_status{pod=\"$cstor_pool\"}",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "cStor Pool Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "sum(openebs_pool_size{pod=\"$cstor_pool\"})/(1024*1024*1024)",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "Used Pool Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "(openebs_used_pool_capacity{pod=\"$cstor_pool\"})/(1024*1024*1024)",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Pool Free Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "(openebs_free_pool_capacity{pod=\"$cstor_pool\"})/(1024*1024*1024)",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openebs_total_read_count{pod=\"$cstor_pool\"})",
     "legendFormat": "read iops"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openebs_total_write_count{pod=\"$cstor_pool\"})",
     "legendFormat": "wrie_iops"
    }
   ]
  }
 ]
}