{
 "title": "OpenEBS / cStor / Volume Replicas dashboard",
 "tags": [ "OpenEBS" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Pool",
    "label": "Pool",
    "query": "label_values(openebs_pool_status,cstor_pool)"
   },
   {
    "name": "spc",
    "label": "spc",
    "query": "label_values(openebs_pool_status{cstor_pool=~\"$Pool\"},storage_pool_claim)"
   },
   {
    "name": "Replicas",
    "label": "Replicas",
    "query": "label_values(openebs_replica_status{cstor_pool=\"$Pool\"}, vol)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pool information",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<html>\n<head>\n\n<script>\nwindow.onload = load('$Pool', '$spc');\n\nfunction getCell(name, value) {\n  return \"<div class=\\\"col-sm\\\"><center><p>\"+name+\"</p><p>\"+value+\"</p></center></div>\";\n}\n\nfunction load(poolNameStr, spcStr) {\nvar poolNameStr = poolNameStr.replace( /[{}]/g, '' );\nvar spcStr = spcStr.replace( /[{}]/g, '' );\n\nz=\"\";\nz+=getCell(\"Pool Name\", poolNameStr);\nz+=getCell(\"CStor pool Cluster\",spcStr);\n\ndocument.getElementById(\"volume-info\").innerHTML = z;\n}\n</script>\n</head>\n\n<body>\n<div class-\"container\">\n<div id=\"volume-info\" class=\"row\"></div>\n</div>\n</body>\n\n</html>"
   }
  },
  {
   "title": "Replica status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "openebs_replica_status{cstor_pool=~\"$Pool\", vol=~\"$Replicas\"}",
     "legendFormat": "{{vol}}"
    }
   ]
  },
  {
   "title": "Replica rebuild count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openebs_rebuild_count{cstor_pool=~\"$Pool\", vol=~\"$Replicas\"}",
     "legendFormat": "{{vol}}"
    }
   ]
  },
  {
   "title": "Replica rebuilding status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "openebs_rebuild_status{cstor_pool=~\"$Pool\", vol=~\"$Replicas\"}",
     "legendFormat": "{{vol}}"
    }
   ]
  },
  {
   "title": "Sync count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openebs_sync_count{cstor_pool=~\"$Pool\",vol=~\"$Replicas\"}",
     "legendFormat": "{{vol}}"
    }
   ]
  },
  {
   "title": "Sync latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "increase(openebs_sync_latency{cstor_pool=~\"$Pool\",vol=~\"$Replicas\"}[2m])",
     "legendFormat": "{{vol}}"
    }
   ]
  },
  {
   "title": "Read IO count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openebs_total_read_count{cstor_pool=~\"$Pool\",vol=~\"$Replicas\"}",
     "legendFormat": "{{vol}}"
    },
    { "legendFormat": "Write IO" }
   ]
  },
  {
   "title": "Read IO in bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "openebs_total_read_bytes{cstor_pool=~\"$Pool\",vol=~\"$Replicas\"}",
     "legendFormat": "{{vol}}"
    }
   ]
  },
  {
   "title": "Read latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "increase(openebs_read_latency{cstor_pool=~\"$Pool\", vol=~\"$Replicas\"}[2m])",
     "legendFormat": "{{vol}}"
    }
   ]
  },
  {
   "title": "Write IO count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openebs_total_write_count{cstor_pool=~\"$Pool\",vol=~\"$Replicas\"}",
     "legendFormat": "{{vol}}"
    }
   ]
  },
  {
   "title": "Write IO in bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openebs_total_write_bytes{cstor_pool=~\"$Pool\",vol=~\"$Replicas\"}",
     "legendFormat": "{{vol}}"
    }
   ]
  },
  {
   "title": "Write latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "increase(openebs_write_latency{cstor_pool=~\"$Pool\", vol=~\"$Replicas\"}[2m])",
     "legendFormat": "{{vol}}"
    }
   ]
  }
 ]
}