{
 "title": "OpenEBS / cStor / Overview",
 "description": "This dashboard gives an overview of OpenEBS cStor status in the cluster.",
 "tags": [
  "OpenEBS",
  "cStor"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "openebs_cstor_label",
    "label": "openebs_cstor_label",
    "query": "label_values(openebs_size_of_volume,openebs_cstor_label)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(sum(container_memory_working_set_bytes{namespace!=\"\"}) by (namespace))"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory usage in namespace $namespace",
   "type": "timeseries",
   "description": "This panel shows the memory usage of cStor Pool across $namespace",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\"} * on (name,pod)group_left(cstor_pool,namespace) openebs_pool_status)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Memory details in namespace $namespace",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\"} * on (name,pod)group_left(cstor_pool,namespace) openebs_pool_status) by(pod,namespace)",
     "legendFormat": "Memory used by pod {{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage in namespace $namespace ",
   "type": "timeseries",
   "description": "This panel shows CPU usage of cStor Pools across $namespace \n",
   "gridPos": { "h": 12, "w": 7, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[1m]) * on (name,pod)group_left(cstor_pool,namespace) openebs_pool_status) * 100",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "CPU details in namespace $namespace",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[1m]) * on (name,pod)group_left(cstor_pool,namespace) openebs_pool_status) by(pod,namespace) * 100",
     "legendFormat": "CPU used by pod {{pod}}"
    }
   ]
  },
  {
   "title": "Pool Status in namespace $namespace",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "openebs_pool_status{namespace=\"$namespace\"}",
     "legendFormat": "A"
    },
    {
     "expr": "openebs_used_pool_capacity{namespace=\"$namespace\"}",
     "legendFormat": "B"
    },
    {
     "expr": "openebs_used_pool_capacity_percent{namespace=\"$namespace\"}",
     "legendFormat": "C"
    },
    {
     "expr": "openebs_free_pool_capacity{namespace=\"$namespace\"}",
     "legendFormat": "D"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"openebs\"} * on (name,pod)group_left(cstor_pool,namespace) openebs_pool_status) by (cstor_pool)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"openebs\"}[1m])  * on (name,pod)group_left(cstor_pool,namespace) openebs_pool_status) by (cstor_pool) * 100"
    }
   ]
  },
  {
   "title": "Persistent Volume in namespace $namespace",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "openebs_volume_status{namespace=\"$namespace\",openebs_cstor_label=~\"$openebs_cstor_label\"}"
    },
    {
     "expr": "openebs_actual_used{namespace=\"$namespace\",openebs_cstor_label=~\"$openebs_cstor_label\"}"
    },
    {
     "expr": "openebs_size_of_volume{namespace=\"$namespace\",openebs_cstor_label=~\"$openebs_cstor_label\"}"
    }
   ]
  }
 ]
}