{
 "title": "OpenEBS / cStor / Overview Dashboard",
 "description": "This dashboard gives an overview of OpenEBS cStor status in the cluster.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(sum(container_memory_working_set_bytes{namespace!=\"\"}) by (namespace))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory usage in namespace $namespace",
   "type": "timeseries",
   "description": "This panel shows the memory usage of cStor Pool across $namespace",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\"} * on (name,pod)group_left(cstor_pool,namespace) openebs_pool_status)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Memory details in namespace $namespace",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\"} * on (name,pod)group_left(cstor_pool,namespace) openebs_pool_status) by(pod,namespace)",
     "legendFormat": "Memory used by pod {{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"} * on (name,pod)group_left(cstor_pool,namespace) openebs_volume_status) by(pod,namespace) * 0.33",
     "legendFormat": "Memory limits by pod {{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"} * on (name,pod)group_left(cstor_pool,namespace) openebs_volume_status) by(pod,namespace) * 0.33",
     "legendFormat": "Memory request by pv {{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage in namespace $namespace ",
   "type": "timeseries",
   "description": "This panel shows CPU usage of cStor Pools across $namespace \n",
   "gridPos": { "h": 12, "w": 7, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[1m]) * on (name,pod)group_left(cstor_pool,namespace) openebs_pool_status) * 100",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "CPU details in namespace $namespace",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[1m]) * on (name,pod)group_left(cstor_pool,namespace) openebs_pool_status) by(pod,namespace) * 100",
     "legendFormat": "CPU used by pod {{pod}}"
    },
    {
     "expr": "sum(rate(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}[1m]) * on (name,pod)group_left(namespace) openebs_volume_status) by(pod,namespace) * 0.33 * 100",
     "legendFormat": "CPU requests by pod {{pod}}"
    },
    {
     "expr": "sum(rate(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}[1m]) * on (name,pod)group_left(namespace) openebs_volume_status) by(pod,namespace) * 0.33 * 100",
     "legendFormat": "CPU limits by pod {{pod}}"
    }
   ]
  },
  {
   "title": "Pool Status in namespace $namespace",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "openebs_pool_status{namespace=\"$namespace\"}",
     "legendFormat": "A"
    },
    {
     "expr": "openebs_used_pool_capacity{namespace=\"$namespace\"}",
     "legendFormat": "B"
    },
    {
     "expr": "openebs_used_pool_capacity_percent{namespace=\"$namespace\"}",
     "legendFormat": "C"
    },
    {
     "expr": "openebs_free_pool_capacity{namespace=\"$namespace\"}",
     "legendFormat": "D"
    }
   ]
  },
  {
   "title": "Memory usage by cStor Pools in namespace $namespace",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum((kube_pod_container_status_ready{namespace=\"openebs\"} == 1)  * on (name,pod)group_left(cstor_pool,namespace) openebs_pool_status) by (cstor_pool)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"openebs\"} * on (name,pod)group_left(cstor_pool,namespace) openebs_pool_status) by (cstor_pool)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"openebs\"}[5m])  * on (name,pod)group_left(cstor_pool,namespace) openebs_pool_status) by (cstor_pool) * 100"
    }
   ]
  },
  {
   "title": "cStor Pod count by nodes of $namespace ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (node)(kube_pod_info{namespace=\"openebs\"} * on (name,pod)group_left(cstor_pool,namespace) openebs_pool_status)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Persistent Volume in namespace $namespace",
   "type": "table",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "openebs_volume_status{namespace=\"$namespace\"}"
    },
    {
     "expr": "openebs_actual_used{namespace=\"$namespace\"}"
    },
    {
     "expr": "openebs_size_of_volume{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "OpenEBS data plane availability ",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 24 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "displayType": "Regular",
     "expr": "avg(avg_over_time((sum without ()(kube_pod_container_status_ready{namespace=\"$namespace\",pod=~\"pvc.*.ctrl.*|pvc.*.rep.*|pvc.*.target.*\"}) / count without ()(kube_pod_container_status_ready{namespace=\"$namespace\",pod=~\"pvc.*.ctrl.*|pvc.*.rep.*|pvc.*.target.*\"}))[1m:5m]))",
     "valueHandler": "Number Threshold"
    },
    {}
   ]
  },
  {
   "title": "Unbounded PV's",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openebs_volume_status{namespace=\"$namespace\"} !=3 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Terminated pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated{namespace=\"$namespace\"} * on (name,pod)group_left(cstor_pool,namespace) openebs_pool_status !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}