{{- $alertRules := dict -}}
{{- range $monitoringAddon,$fields := .Values.openebsMonitoringAddon }}
{{- if (and (hasKey $fields "enabled") ($fields.enabled)) }}
{{- if (hasKey $fields "alertRules") }}
{{- if ($fields.alertRules.enabled) }}
{{ $_ := set $alertRules $monitoringAddon $fields.alertRules.enabled }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- $files := .Files.Glob "rules/**.json" }}
{{- if $files }}
{{- range $fileName, $fileContents := $files }}
{{- $dirName := split "/" $fileName }}
{{- if and (hasKey $alertRules $dirName._1 ) $alertRules }}
{{- $ruleName := regexReplaceAll "(^.*/)(.*)\\.json$" $fileName "${2}" }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ lower (printf "%s-%s" (include "openebs-monitoring.name" $) $ruleName) | trunc 63 | trimSuffix "-" }}
  namespace: {{ template "openebs-monitoring.namespace" $ }}
  labels:
    app: {{ template "openebs-monitoring.name" $ }}
{{ include "openebs-monitoring.labels" $ | indent 4 }}
spec:
{{ $.Files.Get $fileName | indent 2 }}
---
{{- end }}
{{- end }}
{{- end }}
