name: Release Charts

on:
  push:
    paths:
      - "deploy/charts/**"
    branches:
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.0

      - name: Add dependency chart repos
        run: |
          helm repo add kube-prometheus-stack https://prometheus-community.github.io/helm-charts
          helm repo add node-problem-detector https://charts.deliveryhero.io/

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
        with:
          charts_dir: deploy
