name: Release Charts

on:
  push:
    paths:
      - "deploy/charts/**"
    branches:
      - develop
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.18.2

      - name: Add dependency chart repos
        run: |
          helm repo add kube-prometheus-stack https://prometheus-community.github.io/helm-charts
          helm repo add node-problem-detector https://charts.deliveryhero.io/
          helm repo add localpv-provisioner https://openebs.github.io/dynamic-localpv-provisioner

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: deploy
